# ===================================
#  List Behavior Config
# ===================================

list: ~/Modules/System/Models/pluginversion/columns_manage.yaml
modelClass: Modules\System\Models\PluginVersion
noRecordsMessage: backend::lang.list.no_records
showSetup: false
showCheckboxes: true
recordOnClick: $.wn.listToggleChecked(this)
# recordsPerPage: 20

toolbar:
    buttons: list_manage_toolbar
