# ===================================
#  List Behavior Config
# ===================================

title: system::lang.updates.title
list: ~/Modules/System/Models/pluginversion/columns.yaml
modelClass: Modules\System\Models\PluginVersion
noRecordsMessage: backend::lang.list.no_records
recordUrl: system/updates/details/:slug

toolbar:
    buttons: list_toolbar
